POST http://localhost:3003/api/users
Content-Type: application/json

# {
#   "username": "pandapanda89",
#   "name": "Pandu Panda",
#   "password": "pandupanda12"
# }

# {
#   "username": "dankimasta",
#   "name": "Dan Silverstein",
#   "password": "dankidankidanki"
# }

# {
#   "username": "panda",
#   "name": "tresdores",
#   "password": "panda123"
# }
